apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  type: LoadBalancer  # Usa LoadBalancer para exponer Grafana a través de una IP pública
  selector:
    app: grafana
  ports:
    - port: 3000        # Puerto donde Grafana estará expuesto externamente
      targetPort: 3000  # Puerto donde Grafana escucha dentro del contenedor
