apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s   # Intervalo para el scraping de Prometheus

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'usermanagementapi-service'
        static_configs:
          - targets: ['159.203.147.88:80']  # Reemplaza <EXTERNAL-IP> con la IP pública del LoadBalancer y el puerto correcto
