apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
spec:
  selector:
    app: prometheus
  ports:
    - port: 9090       # El puerto donde Prometheus escucha
      targetPort: 9090  # El puerto dentro del contenedor de Prometheus
  type: LoadBalancer   # Tipo de servicio LoadBalancer
