apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver-deployment
  labels:
    app: sqlserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
        securityContext:
        fsGroup: 1000  # Asegura que el contenedor puede escribir en el volumen
      containers:
      - name: sqlserver
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
        - containerPort: 1433
        env:
        - name: SA_PASSWORD
          value: "Your_password123"  # Cambia esto por una contraseña segura
        - name: ACCEPT_EULA
          value: "Y"
        volumeMounts:
        - name: sqlserverdata
          mountPath: /var/opt/mssql
      volumes:
      - name: sqlserverdata
        persistentVolumeClaim:
          claimName: sqlserver-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlserver-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
