apiVersion: v1
kind: Service
metadata:
  name: usermanagementapi-service
spec:
  selector:
    app: usermanagementapi
  ports:
    - protocol: TCP
      port: 80  # Puerto externo
      targetPort: 80  # Puerto dentro del contenedor
  type: LoadBalancer
