apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: usermanagementapi
  name: usermanagementapi
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: usermanagementapi
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/usermanagementapisolution-default: "true"
        io.kompose.service: usermanagementapi
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ConnectionStrings__DefaultConnection
              value: Server=sqlserver;Database=UserManagementDb;User=sa;Password=Your_password123;TrustServerCertificate=True;
          image: usermanagementapi
          name: usermanagementapi
          ports:
            - containerPort: 80
              hostPort: 5000
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
