apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermanagementapi-deployment
  labels:
    app: usermanagementapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: usermanagementapi
  template:
    metadata:
      labels:
        app: usermanagementapi
    spec:
      containers:
      - name: usermanagementapi
        image: lhbotero1985/usermanagementapi:latest  # Imagen de Docker Hub
        ports:
        - containerPort: 80  # Puerto en el que la API escucha dentro del contenedor
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ConnectionStrings__DefaultConnection
          value: "Server=143.198.18.248,30001;Database=UserManagementDb;User=sa;Password=Your_password123;TrustServerCertificate=True;"
